# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

 default_platform(:ios)

# platform :ios do
#   desc "Build app in local"
#   lane :build_local do
#     	build_ios_app(
#       	scheme: "DemoFastlaneCI", 
#       	workspace: "DemoFastlaneCI.xcworkspace",
#       	configuration: "Debug", 
#       	export_method: "development",
# 	output_directory: "./fastlane/build",
# 	output_name: "Deme_create_ipa_from_fastlane",
# 	silent: true,
# 	clean: true
#     	)
#   	end

	# desc "Make build Folder"
	# private_lane :make_build_foder do 
	# sh "mkdir -p ./build" 
  #  end
# end

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
        clean: options[:clean],
        skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
      )
    end
    
    desc "Build app in local"
    lane :build_local do
    	build_ios_app(
        scheme: "DemoFastlaneCI", 
      	workspace: "DemoFastlaneCI.xcworkspace",
      	configuration: "Debug", 
      	export_method: "development",
        xcargs: "-allowProvisioningUpdates",
	      output_directory: "./build",
	      output_name: "Deme_create_ipa_from_fastlane",
	      silent: true,
	      clean: true
    	)
  	end

    desc "Make build Folder"
      private_lane :make_build_foder do 
      sh "mkdir -p ./build" 
     end
      
end
